---
- hosts: all
  become: yes
  tasks:
  - name : Install tomcat
    package:
      name: "{{ pack_name }}"
      state: present
    notify:
    - restart tomcat
  - name: Install additional packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ additional_packages }}"
    notify:
    - restart tomcat
  handlers:
  - name: restart tomcat
    service:
      name: "{{ pack_name }}"
      state: restrated
